apiVersion: core.choreo.dev/v1beta1
kind: ComponentDescriptor
metadata:
  name: team-status-tracker
spec:
  type: webApp
  build:
    buildPackType: dockerfile
    dockerfile:
      path: Dockerfile
  port: 3000
